name: Desktop DMG artifact CI

on:
  push:
    branches: [ "main"]

jobs:
    build-dmg:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode secrets
        run: |
          echo "$SECRETS_FILE" > $GITHUB_WORKSPACE/secrets.properties
        env:
          SECRETS_FILE: ${{ secrets.SECRETS_FILE }}

        # Step 5: Build the DMG file using the custom Gradle task
      - name: Package DMG
        run: ./gradlew packageReleaseDmg

        # Step 6: Upload DMG as an artifact
      - name: Upload DMG as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Oasis_Shoreditch.dmg
          path: composeApp/build/compose/binaries/main-release/dmg/*.dmg

