name: Develop CI

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  build-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode secrets
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > $GITHUB_WORKSPACE/oasis-release-upload-keystore.jks
          echo "$SECRETS_FILE" > $GITHUB_WORKSPACE/secrets.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          SECRETS_FILE: ${{ secrets.SECRETS_FILE }}

      - name: Build with Gradle
        run: ./gradlew build composeApp:assembleDebug compileDebugAndroidTestKotlin testDebugUnitTest linkDebugFrameworkIosX64

      - name: Check
        run: ./gradlew check
