name: iOS Release CI

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  build:
    name: Build iOS App Bundle
    runs-on: macos-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up JDK for Gradle
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # Decode Keystore and secrets.properties
      - name: Decode secrets and keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > $GITHUB_WORKSPACE/oasis-release-upload-keystore.jks
          echo "$SECRETS_FILE" > $GITHUB_WORKSPACE/secrets.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          SECRETS_FILE: ${{ secrets.SECRETS_FILE }}

        # Step 3: Build the KMM Framework
      - name: Build KMM Framework
        run: |
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode

      # Step 3: Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"  # Update this to match your Xcode version

      # Step 4: Build the App
      - name: Build the iOS app
        run: |
          xcodebuild clean build \
            -project $GITHUB_WORKSPACE/iosApp/iosApp.xcodeproj \  # Change to your app workspace
            -scheme iosApp \          # Change to your app scheme
            -sdk iphoneos                   \
            -configuration Release \
            -archivePath $GITHUB_WORKSPACE/build/Oasis.xcarchive

      # Step 5: Export the IPA (App Bundle)
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/Oasis.xcarchive \
            -exportOptionsPlist exportOptions.plist \   # generate exportOptions.plist using Product>Archive in xcode
            -exportPath $GITHUB_WORKSPACE/build

      # Step 6: Upload the IPA as an artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/*.ipa
