name: Android Release CI

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  build-release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Decode Keystore and secrets.properties
      - name: Decode secrets and keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > $GITHUB_WORKSPACE/oasis-release-upload-keystore.jks
          echo "$SECRETS_PROPERTIES" > $GITHUB_WORKSPACE/secrets.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          SECRETS_PROPERTIES_BASE64: ${{ secrets.SECRETS_PROPERTIES }}

      - name: Build with Gradle
        run: ./gradlew :android:assembleRelease :android:bundleRelease

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: 'composeApp/build/outputs/*/release/com.oasis_shoreditch.app.*'
