name: Android Release CI

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  build:
    name: Build iOS App Bundle
    runs-on: macos-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"  # Update this to match your Xcode version

      # Step 4: Build the App
      - name: Build the iOS app
        run: |
          xcodebuild clean build \
            -workspace house-shoreditch/iosApp/iosApp.xcodeproj\  # Change to your app workspace
            -scheme iosApp \          # Change to your app scheme
            -sdk iphoneos                   \
            -configuration Release \
            -archivePath $GITHUB_WORKSPACE/build/Oasis.xcarchive

      # Step 5: Export the IPA (App Bundle)
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/Oasis.xcarchive \
            -exportOptionsPlist exportOptions.plist \   # generate exportOptions.plist using Product>Archive in xcode
            -exportPath $GITHUB_WORKSPACE/build

      # Step 6: Upload the IPA as an artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/*.ipa
