name: iOS Release CI

on:
  push:
    branches: [ none ]

jobs:
  build:
    name: Build iOS App Bundle
    runs-on: macos-latest

    steps:
      # Step : Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step : Set Up JDK for Gradle
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # Step : Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"  # Update this to match your Xcode version

      # Decode Keystore and secrets.properties
      - name: Decode secrets and keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > $GITHUB_WORKSPACE/oasis-release-upload-keystore.jks
          echo "$SECRETS_FILE" > $GITHUB_WORKSPACE/secrets.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          SECRETS_FILE: ${{ secrets.SECRETS_FILE }}

#      # Step : Build the KMM Framework
#      - name: Build KMM Framework
#        run: |
#          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode -PxcodeConfiguration=Release -Pkotlin.native.cocoapods.generateWrapper=false -PxcodeTargetArchs=arm64 -Pkotlin.native.targets=iosArm64,iosSimulatorArm64 --info
      - name: Build KMM Framework
        run: |
          ./gradlew :composeApp:linkReleaseFrameworkIosArm64
          ./gradlew :composeApp:linkReleaseFrameworkIosSimulatorArm64

      # Step : Build the App
      - name: Build the iOS app
        run: |
          xcodebuild clean build \
            -project $GITHUB_WORKSPACE/iosApp/iosApp.xcodeproj \  # Change to your app workspace
            -scheme iosApp \          # Change to your app scheme
            -sdk iphoneos                   \
            -configuration Release \
            -archivePath $GITHUB_WORKSPACE/build/Oasis.xcarchive

      # Step 5: Export the IPA (App Bundle)
      # create provisioning profile https://developer.apple.com/account/resources/profiles/add
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/Oasis.xcarchive \
            -exportOptionsPlist exportOptions.plist \   # generate exportOptions.plist using Product>Archive in xcode
            -exportPath $GITHUB_WORKSPACE/build

      # Step : Upload the IPA as an artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/*.ipa
